name: disaster-dash
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - pandas
  - pip
  - plotly
  - pytest
  - pytest-playwright
  - python=3.11
  - seaborn
  - shiny
  - shinywidgets
  - ibis-framework
  - duckdb
  - pip:
      - anywidget
      - anthropic
      - playwright
      - python-dotenv
      - querychat
      - chatlas

