name: disaster-dash
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - pandas
  - pip
  - plotly
  - python=3.11
  - seaborn
  - shiny
  - shinywidgets
  - pip:
      - anywidget
      - groq
      - python-dotenv
      - querychat
