name: disaster-dash
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - shiny
  - plotly
  - shinywidgets
  - jupyter
  - matplotlib
  - seaborn
  - pip
  - pip:
      - anywidget
      - querychat
      - anthropic
      - python-dotenv